http://localhost:4000/
###
http://localhost:4000/status
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks
###
POST http://localhost:5000/transactions

{
    "to":"lynn",
    "amount":10
}
###
http://localhost:4000/mempool
###
http://localhost:4000/balance/lynn
###
POST http://localhost:2000/peers

{
    "address": "127.0.0.1",
    "port": "5000"
}
###
http://localhost:5000/peers