http://localhost:4000/
###
http://localhost:4000/status
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks
###
POST http://localhost:4000/transactions

{
    "to":"lynn",
    "amount":50
}
###
http://localhost:4000/mempool
###
http://localhost:4000/balance/lynn
###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}