http://localhost:4000/
###
http://localhost:4000/status
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks
###
POST http://localhost:4000/transactions

{
    "to":"lynn",
    "amount":50
}
###
http://localhost:4000/mempool
###
http://localhost:4000/balance/nico